/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

/**
 *
 * @author lidxa
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFundoPainel = new javax.swing.JLabel();
        jInternalFrameBemVindo = new javax.swing.JInternalFrame();
        jPanelInternal = new javax.swing.JPanel();
        jButtonCadGerente = new javax.swing.JButton();
        jButtonCadSala = new javax.swing.JButton();
        jLabelCadastro = new javax.swing.JLabel();
        jButtonCadUsuario = new javax.swing.JButton();
        jLabelAgenda = new javax.swing.JLabel();
        jButtonAgenda = new javax.swing.JButton();
        jLabelImagemPainel = new javax.swing.JLabel();
        jLabelGerenciamento = new javax.swing.JLabel();
        jButtonFecharBemVindo = new javax.swing.JButton();
        jLabelFundoTelaPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCadSala = new javax.swing.JMenuItem();
        jMenuItemCadCliente = new javax.swing.JMenuItem();
        jMenuItemCadUsuários = new javax.swing.JMenuItem();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuItemTelaBemVindo = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        jLabelFundoPainel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_telaprincipal.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrameBemVindo.setResizable(true);
        jInternalFrameBemVindo.setTitle("Welcome to Movie Time");
        jInternalFrameBemVindo.setToolTipText("");
        jInternalFrameBemVindo.setVisible(true);
        jInternalFrameBemVindo.getContentPane().setLayout(null);

        jPanelInternal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelInternal.setLayout(null);

        jButtonCadGerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/chair (1).png"))); // NOI18N
        jButtonCadGerente.setToolTipText("CLIENTES");
        jButtonCadGerente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCadGerenteMouseClicked(evt);
            }
        });
        jButtonCadGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadGerenteActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonCadGerente);
        jButtonCadGerente.setBounds(100, 40, 80, 80);

        jButtonCadSala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3d_1.png"))); // NOI18N
        jButtonCadSala.setToolTipText("SALAS");
        jButtonCadSala.setBorderPainted(false);
        jPanelInternal.add(jButtonCadSala);
        jButtonCadSala.setBounds(270, 40, 80, 80);

        jLabelCadastro.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabelCadastro.setText("Cadastro:");
        jPanelInternal.add(jLabelCadastro);
        jLabelCadastro.setBounds(260, 10, 100, 20);

        jButtonCadUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buildings.png"))); // NOI18N
        jButtonCadUsuario.setToolTipText("USUÁRIOS");
        jPanelInternal.add(jButtonCadUsuario);
        jButtonCadUsuario.setBounds(440, 40, 80, 80);

        jLabelAgenda.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        jLabelAgenda.setText("Agenda:");
        jPanelInternal.add(jLabelAgenda);
        jLabelAgenda.setBounds(20, 180, 70, 20);

        jButtonAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/archive.png"))); // NOI18N
        jButtonAgenda.setToolTipText("AGENDAMENTO");
        jPanelInternal.add(jButtonAgenda);
        jButtonAgenda.setBounds(100, 150, 80, 80);

        jLabelImagemPainel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_telaprincipal.jpg"))); // NOI18N
        jPanelInternal.add(jLabelImagemPainel);
        jLabelImagemPainel.setBounds(10, 0, 600, 240);

        jInternalFrameBemVindo.getContentPane().add(jPanelInternal);
        jPanelInternal.setBounds(-10, 40, 610, 240);

        jLabelGerenciamento.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabelGerenciamento.setText("Sistema de Gerenciamento:");
        jInternalFrameBemVindo.getContentPane().add(jLabelGerenciamento);
        jLabelGerenciamento.setBounds(150, 10, 320, 20);

        jButtonFecharBemVindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon (1).png"))); // NOI18N
        jButtonFecharBemVindo.setToolTipText("FECHAR");
        jButtonFecharBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharBemVindoActionPerformed(evt);
            }
        });
        jInternalFrameBemVindo.getContentPane().add(jButtonFecharBemVindo);
        jButtonFecharBemVindo.setBounds(550, 0, 40, 30);

        getContentPane().add(jInternalFrameBemVindo);
        jInternalFrameBemVindo.setBounds(100, 20, 610, 310);

        jLabelFundoTelaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/8757bc0b7c5e69d.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoTelaPrincipal);
        jLabelFundoTelaPrincipal.setBounds(0, 0, 800, 375);

        jMenuCadastro.setText("Cadastros");

        jMenuItemCadSala.setText("Sala");
        jMenuItemCadSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadSalaActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadSala);

        jMenuItemCadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/chair_1.png"))); // NOI18N
        jMenuItemCadCliente.setText("Cliente");
        jMenuItemCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadClienteActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadCliente);

        jMenuItemCadUsuários.setText("Usuários");
        jMenuItemCadUsuários.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadUsuáriosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadUsuários);

        jMenuBar1.add(jMenuCadastro);

        jMenuFerramentas.setText("Ferramentas");

        jMenuItemTelaBemVindo.setText("Tela Bem-Vindo");
        jMenuItemTelaBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTelaBemVindoActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemTelaBemVindo);

        jMenuBar1.add(jMenuFerramentas);

        jMenuSair.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(820, 433));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCadSalaActionPerformed

    private void jMenuItemCadUsuáriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadUsuáriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCadUsuáriosActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jButtonCadGerenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCadGerenteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCadGerenteMouseClicked

    private void jButtonCadGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadGerenteActionPerformed
     FromCliente obj = new FromCliente();
     obj.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButtonCadGerenteActionPerformed

    private void jButtonFecharBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharBemVindoActionPerformed
     jInternalFrameBemVindo.dispose();
             
        
    }//GEN-LAST:event_jButtonFecharBemVindoActionPerformed

    private void jMenuItemTelaBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTelaBemVindoActionPerformed
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemTelaBemVindoActionPerformed

    private void jMenuItemCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadClienteActionPerformed
    new FromCliente().setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCadClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgenda;
    private javax.swing.JButton jButtonCadGerente;
    private javax.swing.JButton jButtonCadSala;
    private javax.swing.JButton jButtonCadUsuario;
    private javax.swing.JButton jButtonFecharBemVindo;
    private javax.swing.JInternalFrame jInternalFrameBemVindo;
    private javax.swing.JLabel jLabelAgenda;
    private javax.swing.JLabel jLabelCadastro;
    private javax.swing.JLabel jLabelFundoPainel;
    private javax.swing.JLabel jLabelFundoTelaPrincipal;
    private javax.swing.JLabel jLabelGerenciamento;
    private javax.swing.JLabel jLabelImagemPainel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenuItem jMenuItemCadCliente;
    private javax.swing.JMenuItem jMenuItemCadSala;
    private javax.swing.JMenuItem jMenuItemCadUsuários;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemTelaBemVindo;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanelInternal;
    // End of variables declaration//GEN-END:variables
}
